# Generated by Django 5.1.4 on 2025-01-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="views",
        ),
        migrations.AddField(
            model_name="post",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовать"),
        ),
    ]
