# Generated by Django 5.1.4 on 2025-02-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_description_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(null=True, verbose_name="Цена продукта"),
        ),
    ]
