# Generated by Django 5.1.4 on 2025-02-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
